# Example Applicants list.
APPLICANTS_DB = {
    "APP001": {
        "name": "John Smith",
        "business_name": "Smith Consulting LLC",
        "credit_score": 720,
        "annual_personal_income": 95000,
        "business_annual_revenue": 280000,
        "debt_to_income": 0.28,
        "business_age_years": 5,
        "industry": "consulting",
        "owner_equity_percent": 100,
        "previous_loans": 1,
        "previous_loans_status": "paid_in_full",
        "dscr": 1.85,
        "state": "California",
        "us_citizen": True
    },
    "APP002": {
        "name": "Jane Doe",
        "business_name": "Doe's Diner",
        "credit_score": 580,
        "annual_personal_income": 45000,
        "business_annual_revenue": 65000,
        "debt_to_income": 0.55,
        "business_age_years": 1.5,
        "industry": "restaurant",
        "owner_equity_percent": 75,
        "previous_loans": 0,
        "previous_loans_status": None,
        "dscr": 0.95,
        "state": "Texas",
        "us_citizen": True
    },
    "APP003": {
        "name": "Robert Wilson",
        "business_name": "Wilson Tech Solutions",
        "credit_score": 785,
        "annual_personal_income": 180000,
        "business_annual_revenue": 1200000,
        "debt_to_income": 0.22,
        "business_age_years": 8,
        "industry": "technology",
        "owner_equity_percent": 60,
        "previous_loans": 3,
        "previous_loans_status": "paid_in_full",
        "dscr": 2.40,
        "state": "Washington",
        "us_citizen": True
    },
    "APP004": {
        "name": "Maria Garcia",
        "business_name": "Garcia Beauty Salon",
        "credit_score": 680,
        "annual_personal_income": 62000,
        "business_annual_revenue": 145000,
        "debt_to_income": 0.41,
        "business_age_years": 3,
        "industry": "beauty_services",
        "owner_equity_percent": 100,
        "previous_loans": 0,
        "previous_loans_status": None,
        "dscr": 1.35,
        "state": "Florida",
        "us_citizen": True,
        "minority_owned": True
    },
    "APP005": {
        "name": "David Chen",
        "business_name": "Chen Construction Inc",
        "credit_score": 710,
        "annual_personal_income": 120000,
        "business_annual_revenue": 850000,
        "debt_to_income": 0.38,
        "business_age_years": 6,
        "industry": "construction",
        "owner_equity_percent": 80,
        "previous_loans": 2,
        "previous_loans_status": "current",
        "dscr": 1.55,
        "state": "Illinois",
        "us_citizen": True,
        "contracts_in_pipeline_months": 14
    },
    "APP006": {
        "name": "Sarah Johnson",
        "business_name": "Green Leaf Cannabis Co",
        "credit_score": 740,
        "annual_personal_income": 110000,
        "business_annual_revenue": 600000,
        "debt_to_income": 0.30,
        "business_age_years": 4,
        "industry": "cannabis",
        "owner_equity_percent": 50,
        "previous_loans": 0,
        "previous_loans_status": None,
        "dscr": 1.70,
        "state": "Colorado",
        "us_citizen": True
    },
    "APP007": {
        "name": "Michael Brown",
        "business_name": "Brown Logistics LLC",
        "credit_score": 695,
        "annual_personal_income": 88000,
        "business_annual_revenue": 420000,
        "debt_to_income": 0.45,
        "business_age_years": 2.5,
        "industry": "trucking",
        "owner_equity_percent": 100,
        "previous_loans": 1,
        "previous_loans_status": "paid_in_full",
        "dscr": 1.30,
        "state": "Georgia",
        "us_citizen": True,
        "veteran": True
    },
    "APP008": {
        "name": "Emily Rodriguez",
        "business_name": "Rodriguez Boutique",
        "credit_score": 660,
        "annual_personal_income": 52000,
        "business_annual_revenue": 95000,
        "debt_to_income": 0.42,
        "business_age_years": 1,
        "industry": "retail",
        "owner_equity_percent": 100,
        "previous_loans": 0,
        "previous_loans_status": None,
        "dscr": 1.10,
        "state": "Arizona",
        "us_citizen": True,
        "minority_owned": True,
        "women_owned": True
    },
    "APP009": {
        "name": "James Anderson",
        "business_name": "Anderson Startup Inc",
        "credit_score": 725,
        "annual_personal_income": 85000,
        "business_annual_revenue": 35000,
        "debt_to_income": 0.32,
        "business_age_years": 0.8,
        "industry": "technology",
        "owner_equity_percent": 70,
        "previous_loans": 0,
        "previous_loans_status": None,
        "dscr": 0.85,
        "state": "New York",
        "us_citizen": True
    },
    "APP010": {
        "name": "Lisa Patel",
        "business_name": "Patel Healthcare Services",
        "credit_score": 760,
        "annual_personal_income": 145000,
        "business_annual_revenue": 980000,
        "debt_to_income": 0.25,
        "business_age_years": 7,
        "industry": "healthcare",
        "owner_equity_percent": 90,
        "previous_loans": 2,
        "previous_loans_status": "paid_in_full",
        "dscr": 2.10,
        "state": "Massachusetts",
        "us_citizen": True,
        "minority_owned": True,
        "women_owned": True
    }
}